### ISSUE TITLE
[Website] update landing page - https://lfnetworking.org/cloud-native-networking/

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#1]
**Describe the update:**
- update landing page - https://lfnetworking.org/cloud-native-networking/

**Describe why update is needed**
- the 1st version of the landing page was released in Nov 2023
- Additional details of the initiative are now available 

**Additional context**
- Update the name (CNTI)
- Add link to wiki
- Make sure all 3 pillars of our work are listed (best practices, test catalog, certification)

**Tasks**

- [x] Create draft doc > https://docs.google.com/document/d/1lF3rR3z39B0troqducYxd0vMT8WE9hvFWC3OCphc760/edit
- [x] Draft new landing page content
- [x] Share draft with LFN staff and request updates
- [ ] QA published changes
- [ ] Close issue

**Comment by lixuna** [comment]
It looks like the web team has made the requested changes. 

Next steps: 
- please QA https://lfnetworking.org/cloud-native-telecom-initiative/ 
- Are any additional changes needed?

**Comment by Smitholi67** [comment]
/LGTM.  If possible, it could be worth an effort to make the link to participation even more obvious.  It currently is at the very bottom of the landing page.  Perhaps we could add an icon/link in the top part as well?  It might be a simple "Collaborate with us" as a callout or something similar with a link to the wiki.

**Comment by lixuna** [comment]
Minor typo to be fixed: 

- remove end quote from 
` If you are interested in participating and advancing this initiative, please consider engaging in one or more of our focus areas. See details at: [LF Networking Wiki | Cloud Native Telecom Initiative (CNTI)](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592).”`

**Comment by lixuna** [comment]
New request: 
- add hyperlink to https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592 

What we have now:
"The Cloud Native Telecom Initiative will focus on 3 key areas:"

What we could have instead: 
The **[Cloud Native Telecom Initiative](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592)** will focus on 3 key areas:

**Comment by lixuna** [comment]
New feature: 
- add a button in the hero image that says "Let's work together"
- clicking on button opens https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592 in a new tab

See examples of hero image button at:
- https://project-emco.io/
- https://xgvela.org/
- https://l3af.io/

<img width="1177" alt="Screenshot 2024-02-12 at 12 13 33 PM" src="https://github.com/lfn-cnti/cnti/assets/11701267/bfcd2855-2c29-4d19-9537-7e0252409696">
<img width="1180" alt="Screenshot 2024-02-12 at 12 20 10 PM" src="https://github.com/lfn-cnti/cnti/assets/11701267/31e8f041-13b9-442a-b07a-5f2dda381bb3">
<img width="1151" alt="Screenshot 2024-02-12 at 12 20 41 PM" src="https://github.com/lfn-cnti/cnti/assets/11701267/1f8de768-7c07-49cb-87ed-a760556dbcd9">

**Comment by lixuna** [comment]
Quick design mock - LFN Web Team to follow their normal LFN style guide for implementation

<img width="1167" alt="CNTI-CTA" src="https://github.com/lfn-cnti/cnti/assets/11701267/6a0ac581-516e-47f2-96e6-8762ee8c3e9f">

**Comment by lixuna** [comment]
Quick design mock - LFN Web Team to follow their normal LFN style guide for implementation

<img width="1167" alt="CNTI-CTA" src="https://github.com/lfn-cnti/cnti/assets/11701267/821e593f-dac0-4f26-bfb5-29d11673ac5b">

**Comment by lixuna** [comment]
Monday, Feb 12, 2024 - I sent an email to LFN Staff to ask for assistance fixing one bug and implementing 2 new features

Typo: 
remove end quote from:
If you are interested in participating and advancing this initiative, please consider engaging in one or more of our focus areas. See details at: [LF Networking Wiki | Cloud Native Telecom Initiative (CNTI)](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592).”

Feature #1:
add hyperlink (https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592) to  [Cloud Native Telecom Initiative](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592) 
What we have now:

"The Cloud Native Telecom Initiative will focus on 3 key areas:"

What we would like to see:

The [Cloud Native Telecom Initiative](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592) will focus on 3 key areas:



Feature #2:

add a call-to-action button in the hero image/blue area that says "Let's Work Together"
clicking on "Let's Work Together" button opens https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592 in a new tab
See design mockup at https://github.com/lfn-cnti/cnti/issues/1#issuecomment-1939307673

**Comment by lixuna** [comment]
Wed, Feb 21 - the request has been shared with LFN web team for updates

**Comment by lixuna** [comment]
Fri, Feb 23 - 2 features have been added to https://lfnetworking.org/cloud-native-telecom-initiative/

There are 2 new bugs
1. the menu button now incorrectly says "CNF PROGRAM" - it should be Cloud Native Telecom Initiative or CNTI - I will ask the web team to change this back to "Cloud Native Telecom Initiative"
2. The final sentence was removed entirely. The request was to remove the unneccessary end quotation mark ("). I will ask the web team to add this sentence back > "If you are interested in participating and advancing this initiative, please consider engaging in one or more of our focus areas. See details at: [LF Networking Wiki | Cloud Native Telecom Initiative (CNTI)](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592).”



<img width="1038" alt="Screenshot 2024-02-23 at 12 03 04 PM" src="https://github.com/lfn-cnti/cnti/assets/11701267/e7559827-5377-43ca-a203-72dee7c758c4">

**Comment by lixuna** [comment]
Feb 23, 2024 - closing this issue as the 2 features have been implemented. New issues will be created for followup items.
