### ISSUE TITLE
[Marketing] update @cnfcert twitter account to reflect CNTI > account is now called: @lfncnti

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#10]
**Describe the update:**
update @cnfcert twitter account to reflect CNTI

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- https://twitter.com/cnfcert
- 

**Tasks**
- [x] Update name from CNF Certification by # CNCF > tbd
- [ ] Update logo > tbd in lfn-cnti/cnti#7 
- [x] Update bio from 📞📱☎️📡🌐Beta release for Cloud native Network Function Certification program - see more at http://cncf.io/cnf > tbd
- [x] Update website from https://github.com/cncf/cnf-certification > tbd

**Comment by lixuna** [comment]
Logo blocked by #7 

Others changes have been made to https://twitter.com/lfncnti


<img width="680" alt="Screenshot 2024-02-13 at 4 57 50 PM" src="https://github.com/lfn-cnti/cnti/assets/11701267/2b651086-a80e-496b-ad73-d2b49e183ee2">

**Comment by lixuna** [comment]
I'll close this, and add an action item "update logo for https://twitter.com/lfncnti" to #7
