### ISSUE TITLE
[Website] Updates to landing page - https://lfnetworking.org/cloud-native-networking/

### ISSUE THREAD

**Issue by Smitholi67** [lfn-cnti/cnti#11]
**Describe the update:**
- update landing page - https://lfnetworking.org/cloud-native-networking/

**Describe why update is needed**
- the 1st version of the landing page was released in Nov 2023
- Additional request from the LFN TAC on Feb 21, 2024 to incorporate additional text on the landing page that will:
   -  Provides a short explanation for the unique challenges of telco networking and the benefits that taking a cloud native approach can bring.   The goal is to add brief text to the landing page that further motivates/explains why the CNTI is of value.

**Tasks**

- [x] Create draft doc > https://docs.google.com/document/d/1RcEfH4WGvFhUdpfU68RKV7icoVDTvLvKsltkxqbCz8Y/edit
- [ ] Draft new landing page content
- [ ] Share draft with LFN staff and request updates
- [ ] QA published changes
- [ ] Close issue

**Comment by lixuna** [comment]
@Smitholi67 here is the existing landing page draft if you want to use it https://docs.google.com/document/d/1lF3rR3z39B0troqducYxd0vMT8WE9hvFWC3OCphc760/edit#heading=h.1i5sxjm9swy1
