### ISSUE TITLE
[General] Architecture slide for CNTi (part of LFN Project induction)

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#16]
**Describe the update:**
- Architecture slide for CNTi is needed for the LFN Project induction process
- LFN Project induction slides in progress.  https://wiki.lfnetworking.org/display/LN/CNTI+Proposal

**Tasks:**

- [x] Review https://wiki.lfnetworking.org/display/LN/CNTI+Proposal
- [x] Review other induction slides for inspiration, like https://wiki.lfnetworking.org/display/LN/Nephio+Induction+Proposal 
- [x] Draft an architecture diagram for the CNTi components, focus areas, code building blocks and how it all relates to each other https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592
- [ ] Peer review

**Comment by lixuna** [comment]
CNTi WIP Diagrams slides: https://docs.google.com/presentation/d/1ZohcWMJHrhrFw-n5l_JNYAPosrdmOR2eQNt-mJKnAFw/edit#slide=id.g26e423a911d_1_282

**Comment by lixuna** [comment]
Other diagrams available in the D&TF presentations. 

See https://github.com/lfn-cnti/cnti/issues/15#issuecomment-2099282715
