### ISSUE TITLE
[General] Aspirational Roadmap slide for CNTi (part of LFN Project induction)

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#17]
**Describe the update:**
- Aspirational Roadmap slide for CNTi is needed for the LFN Project induction process
- LFN Project induction slides in progress.  https://wiki.lfnetworking.org/display/LN/CNTI+Proposal

**Tasks:**

- [x] Review https://wiki.lfnetworking.org/display/LN/CNTI+Proposal
- [x] Review other induction slides for inspiration, like https://wiki.lfnetworking.org/display/LN/Nephio+Induction+Proposal 
- [x] Draft an Aspirational Roadmap slide for the CNTi focus areas > WIP: https://docs.google.com/presentation/d/16RyA9uhOgQqOy-IUG-Yb_PP0Fw-6ldvFj5RMPfY6Tgk/edit#slide=id.g2cb005540b4_0_287
- [ ] Add content as prioritized by community
- [ ] Peer review

**Comment by lixuna** [comment]
WIP slide in https://docs.google.com/presentation/d/16RyA9uhOgQqOy-IUG-Yb_PP0Fw-6ldvFj5RMPfY6Tgk/edit#slide=id.g2cb005540b4_0_558

Initial ideas: 

**Best Practices**
- Release schedule: tbd 

Roadmap:
- Document essential certification best practices 
- more tbd

**Test Suite**
- Release schedule: quarterly

Roadmap:
- Improve test case definition readability
- Rewrite software (from Crystal Lang to Ruby and Gerkin)
- more tbd

**Certification**
- Release Schedule: 2 releases per year

Roadmap:
- Introduce new Certification Levels (Silver, Gold, Platinum)
- more tbd

**Comment by lixuna** [comment]
@Smitholi67 FYI - I added a blocked label for this repo
