### ISSUE TITLE
[Press Release] Prepare a short update on CNTi for Opening Keynote & ONE Summit Day 1 Press Release

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#19]
**Describe the update:**
- Prepare a one or two sentence update on CNTi for ONE Summit Opening Keynote & Day 1 Press Release

**Describe why update is needed**
- to share updates made on the CNTI program
- to announce availability of the CNTi Certification v2.0 release
- to promote the session about CNTI at ONE Summit on May 1  and D&TF on May 3 (optional)

**Additional context**
- W. Watson and Olivier are scheduled to speak at ONE Summit, which can be promoted in the blog post
- if GB votes "greenlight" on April 29, then CNTi Certification v2.0 can be launched at ONE Summit

**Tasks:**

- [ ] start a drafted document - one or 2 sentences long
- [ ] share document with Jill, LFN 
- [ ] iterate on short update
- [ ] peer review
- [ ] final draft of update
- [ ] tbd

**Comment by Smitholi67** [comment]
@lixuna @taylor - Something like this?

LF Networking today announced the availability of the Cloud Native Teleco Initiative (CNTi) Certification Program. The CNTi Certification Program, powered by the CNTi Test Suite, supports products within a certified Kubernetes environment, helping NEPs and CNF creators showcase their commitment to cloud native best practices. The goal of the CNTi Certification Program is to help Communication Service Providers (CSPs) and other end users identify networking applications vendors who demonstrate adherence to cloud native best practices in their products. The Cloud Native Telecom Initiative (CNTi), a unification of the Cloud Native Computing Foundation (CNCF) telecom initiatives and the Linux Foundation Networking (LFN), aims to advance cloud native telecom development, deployment, and operations.
