### ISSUE TITLE
[Keynote] Prepare a short update on CNTi for ONE Summit Keynote

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#20]
**Describe the update:**
- Prepare a short update on CNTi for ONE Summit Keynote
- content is subject to change, pending GB vote on April 29

**Describe why update is needed**
- to share updates made on the CNTI program
- to announce availability of the CNTi Certification v2.0 release
- to promote the session about CNTI at ONE Summit on May 1 

**Additional context**
- Taylor and Olivier are scheduled to speak at ONE Summit, which can be promoted in the blog post
- if GB votes "greenlight" on April 29, then this press release can be published on April 30 and CNTi Certification v2.0 can be launched at ONE Summit

**Tasks:**

- [ ] start a drafted document 
- [ ] share document with Jill, LFN 
- [ ] iterate on short update
- [ ] peer review
- [ ] final draft of update
- [ ] tbd
