### ISSUE TITLE
[Presentation] slides and/or demo video of CNTi mini-booth/kiosk at ONE Summit 2024

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#23]
### Description 
- Prepare slides or recorded video of CNTi for CNTi mini-booth/kiosk at ONE Summit 2024

### Details:
- prepare something about CNTi to display on the monitor at the CNTi mini-booth/kiosk
- to be shown on a loop 
- to be shown on Tuesday, April 30 and Wednesday, May 1

### Tasks

- [x] Draft an outline of content to be displayed on the booth monitor
- [x] prepare slides with content 
- [x] share draft with community 
- [x] peer review 
- [x] finalized version to be sent to LFN Staff - tbd

**Comment by lixuna** [comment]
Here's an example of CNF Certification Program's "ONE Summit 2022: CNCF Booth Presentation_Draft" for inspiration:

https://docs.google.com/presentation/d/13RNT6ulQuOX6XG-l3xB10FLM_EOmqRMOJEiXqIjNuaY/edit#slide=id.g18802fc07d8_0_606

**Comment by lixuna** [comment]
Here is a WIP: draft for [ONE-Summit-2024-CNTi-Booth-Presentation](https://docs.google.com/presentation/d/1gm3RJurSO2ArNVrYQVdO7TPgjz-91ojSM_uk0PlT99U/edit#slide=id.p1)

**Comment by Smitholi67** [comment]
@martin-mat and @Smitholi67 will create a short booth presentation no later than 4/26/2024.  The plan is to try and reuse some key slides from the presentation that will be given by Olivier and Watson.

**Comment by jillLovato** [comment]
> @martin-mat and @Smitholi67 will create a short booth presentation no later than 4/26/2024. The plan is to try and reuse some key slides from the presentation that will be given by Olivier and Watson.

Checking in on the booth slides for next week - please let me know when they are ready. We will need them noi later than Monday morning to convert, download, and set up the booth. Thanks1

**Comment by Smitholi67** [comment]
Shared with @jillLovato :  https://docs.google.com/presentation/d/1E94iokxMok_g-Wi5NcvkJx1ak2fSZZJxQ0Mmd3NdKmU/edit?usp=sharing
