### ISSUE TITLE
[Design] Create "artwork" repo to store the icons and badges

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#24]
**Describe the update:**
- Create repo called https://github.com/lfn-cnti/artwork

**Describe why update is needed**
- Artwork repo to store the icons and badges

**Tasks**
- [x] Create repo called https://github.com/lfn-cnti/artwork
- [x] Create new folder for cnti-logo 
- [x] Create new folder for cnti-badge

**Comment by lixuna** [comment]
Refs #7 and https://github.com/lfn-cnti/certification/issues/68

**Comment by lixuna** [comment]
https://github.com/lfn-cnti/artwork

**Comment by lixuna** [comment]
https://docs.google.com/document/d/15GhPSsapi3i2PyNLU6WcB70x_J0-gQCvtfmUs0xhMOo/edit#bookmark=id.l2vw05cuy302

More folders:

Horizontal - displaying the logo + the CNTi name in-line
- Black
  - Svg
  - Png 
- Color 
  - Svg
  - Png 
- white 
  - Svg
  - Png 
Icon - displaying the logo only (no words)
- Black
  - Svg
  - Png 
- Color 
  - Svg
  - Png 
- white 
  - Svg
  - Png 
Stacked - displaying the logo on top or beneath the name CNTi
- Black
  - Svg
  - Png 
- Color 
  - Svg
  - Png 
- white 
  - Svg
  - Png

**Comment by lixuna** [comment]
more folders: 

## cnti-badge

### Horizontal
- Black
- Color 
- white 

### Icon
- Black
- Color 
- white 

### Stacked
- Black
- Color 
- white

**Comment by lixuna** [comment]
@Smitholi67 the logo and badge folders are available for you to upload the files when they are available. Please let me know if you have any questions

<img width="971" alt="Screenshot 2024-04-22 at 5 55 58 PM" src="https://github.com/lfn-cnti/cnti/assets/11701267/472388df-55d3-49c3-8106-6773c843be05">
