### ISSUE TITLE
[Admin] Edit ADMINs of CNTi mailing list lfn-cnti@lists.lfnetworking.org 

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#29]
**Describe the update:**
- Edit ADMINs of CNTi mailing list lfn-cnti@lists.lfnetworking.org 
- reference lfn-cnti/certification#84 

**Describe why update is needed**
- add new admins
- remove emeritus admins

**Tasks**
- [ ] add LJ, if needed
- [ ] add Olivier, if needed
- [ ] add new members, as needed 
- [ ] remove emeritus vulk members
- [ ] tbd
