### ISSUE TITLE
[Design] Logo for CNTi

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#7]
**Describe the update:**
- Create logo for LFN [Cloud Native Telecom Initiative (CNTi)](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592) 
- FYI - stylized acronym = "CNTi" 

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- Previous iteration of CNF Certification did not have a logo
- If CNTI is going to be induced as an LFN project, it would be nice to have a logo

**Tasks**
- [x] request assistance from design team (or open source contributor) to create CNTI logo mocks
- [x] search for design guidelines that LFN may have published online - see if LFN published any design resources, like the CNCF's artwork README https://github.com/cncf/artwork/blob/main/README.md - N/A
- [x] brainstorm ideas for the CNTI logo
- [x] circulate mocks with community
- [x] community vote on favorite logo ideas
- [x] second round of creating design mocks/circulating/voting, if needed
- [x]  use logo on landing page, social media, presentations, etc
- [ ] update logo for https://twitter.com/lfncnti

**Comment by Smitholi67** [comment]
Olivier will meet with MATRIXX's Design Director on March 7th to begin work.  A bit of a delay due to MWC.

**Comment by lixuna** [comment]
March 18, 2024 update: 
- MATRIXX Marketing Head granted approval to their design team to create a CNTI logo/badge.

**Comment by lixuna** [comment]
USPTO Image requirements

* Saved as JPG file that does not exceed 5 MB
* Image has a resolution of no less than 300 dots per inch (“DPI”) and no more than 350 DPI
* Image height and width is no less than 250 pixels and no more than 944 pixels (e.g., a valid pixel dimension is 640 x 480 pixels) (NOTE: this isn't a strict requirement, if the design is very long or tall).
* Mark images must not include the trademark, service mark or registration symbols (TM, SM or ®)
* Mark images should be submitted with as little white space around the design as possible
* If color is claimed as part of this mark, the image needs to be in the exact colors as will be used. We will also need to list the colors claimed in the application.
* If color is not claimed as part of this mark, the image needs to be in pure black and white (no grayscale).
* Images created on a Macintosh using Adobe Photoshop or Illustrator must be properly saved with appended file extensions .jpg for use on a Windows system. The USPTO cannot open image files that are not properly saved prior to attachment to the application.
* Adobe Photoshop/Illustrator users must ensure that images are saved with the RGB color scheme. The USPTO cannot accept the CYMK color scheme.
* Do not zip your image files or add any additional compression. JPG files are already compressed.

**Comment by Smitholi67** [comment]
Mocks can be found here:  https://drive.google.com/file/d/1rqGbQlS7koGDu0O8cw_2yIUcIbVP5pYs/view?usp=sharing

**Comment by electrocucaracha** [comment]
I prefer the second option, maybe it's me but I associate the horizontal bars with Ericsson logo

**Comment by jillLovato** [comment]
I'm good with either #1 or #2; the third logo looks too much like  the Hubspot logo and the Orange Theory Fitness logo:

<img width="381" alt="Screenshot 2024-04-11 at 1 46 33 PM" src="https://github.com/lfn-cnti/cnti/assets/166747062/43f58a3e-4895-4c9b-8eb6-a88f8c78b2d5">
<img width="267" alt="Screenshot 2024-04-11 at 1 46 55 PM" src="https://github.com/lfn-cnti/cnti/assets/166747062/0de6f2f7-27f6-408d-813c-0c3536f27917">

**Comment by tomkivlin** [comment]
I think 2 best shows the two main aspects (cloud and telco). I know trlco isn't just wireless/radio but it's a well recognised thing. 

1 and 3 don't show the telco bit, to me.

**Comment by petorre** [comment]
> I think 2 best shows the two main aspects (cloud and telco). I know trlco isn't just wireless/radio but it's a well recognised thing.
> 
> 1 and 3 don't show the telco bit, to me.

I agree.

**Comment by martin-mat** [comment]
I agree with option 2 with 4 bars.

**Comment by horecoli** [comment]
I like the combination of green and blue colors in option 2, so #2 is my choice.

**Comment by kosstennbl** [comment]
Same, 2 looks nice: cloud as a representation and vertical bars as something representing "good connection, reliability". Coloring scheme is also looking good, in my opinion - option 1 looks too cold.

**Comment by lixuna** [comment]
Commenting period is over. Decision: Logo # 2 with 4 bars instead of 5

**Comment by lixuna** [comment]
@Smitholi67 to store the files,  the logo and badge folders are available at https://github.com/lfn-cnti/artwork

**Comment by lixuna** [comment]
Image size recommendations for Twitter: 
- https://help.twitter.com/en/managing-your-account/how-to-customize-your-profile

Header photo, also known as a “banner” 
- recommended dimensions are 1500x500 pixels
Profile photo 
- recommended dimensions are 400x400 pixels
