### ISSUE TITLE
[General] start the LFN Project induction process for CNTI

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#8]
**Describe the update:**
- In the LFN TAC meeting on Wed, Feb 7, the TAC requested the CNTI community to start the LFN Project induction process
- https://wiki.lfnetworking.org/display/LN/Getting+Started+With+LFN 
- Wed, Feb 7 LFN TAC meeting notes at https://wiki.lfnetworking.org/display/LN/2024-02-07+TAC+Minutes

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- LFN prefers to have all efforts under their Project structure

**Tasks:**

- [x] Review https://wiki.lfnetworking.org/display/LN/Getting+Started+With+LFN
- [x] Review https://wiki.lfnetworking.org/display/LN/How+to+Join+the+LFN+as+a+Project
- [x] Start [Project Proposal](https://wiki.lfnetworking.org/display/LN/Project+Proposals)
- [ ] #16 
- [ ] #17 
- [ ] tbd

**Comment by Smitholi67** [comment]
CNTI Proposal in progress - https://wiki.lfnetworking.org/display/LN/CNTI+Proposal

**Comment by lixuna** [comment]
Following the [LFN Lifecycle States & Guidelines](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=101352484)[LFN Lifecycle States & Guidelines](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=101352484) at https://wiki.lfnetworking.org/pages/viewpage.action?pageId=101352484, it looks like CNTi meets the Incubating Project requirements:

- "Sandbox | The Sandbox stage is designed to provide a lightweight entry process for new projects that align with the LFN mission and meet the  It is ideal for early-stage projects that require time to explore their community, governance, and technical roadmap.  Project proposals should meet the (sic)"
- "Incubation | The project meets all the prerequisites for the Sandbox stage. Furthermore, the Incubation stage is intended for projects that have implemented open source best practices, including having a varied contributor base and adhering to open governance principles. Projects at this stage should actively cooperate with other LFN projects, engage in cross-LFN endeavors, or contribute to broadening or reinforcing the LFN's scope."

**Comment by Smitholi67** [comment]
blocked by https://github.com/lfn-cnti/cnti/issues/16
blocked by https://github.com/lfn-cnti/cnti/issues/17

**Comment by Smitholi67** [comment]
Met with LJ and Ranny on 4/16/2024 to do a first run through of the material.  Actions to address:

1.  We should have the CNTI charter reviewed by Scott Nicholas (LF Legal team) specializing in Project Formation.
2.  We are asked to consider releases even for our Best Practices.  Most likely, it is about articulating how Best Practices, Tests, and Certifications are released and dependencies between managed. 
3. We can likely continue with Co-Chairs and no Chair (Co-Chairs are the voting body)
4. We were asked to consider how OpenSSF and how it might be of help to CNTi.  Do not have to solve now.
5. We were asked to also include a Release Management Process.
6. A brief discussion on Project Lifecycle Stage for CNTI.  Likely Incubation is the right level but to be discussed in the community.

**Comment by lixuna** [comment]
@Smitholi67 for the Release Plan/process in the induction proposal, here is an example of how Network Service Mesh plans their releases - ultimately, the community is given options for each release. 

These examples may be useful for the Test Suite Focus Area, as the contributions are gaining traction.

#### Release v1.14.0 schedule:

### Options:

[Current] 8-weeks release cycle:
- Dev: 6w
- Bug fix: 1w
- Release candidate testing: 1w
- Release date:  21 May 2024

8-weeks release cycle:

- Dev: 4w
- Bug fix: 1w
- Release candidate testing: 3w
- Release date: 21 May 2024

10-weeks release cycle:

- Dev: 6w
- Bug fix: 1w
- Release candidate testing: 3w
- Release date:  4 Jun 2024

Floating release cycle:

- Dev: 6w
- Bug fix: 1w
- Release candidate testing: 1-3w
- Release interval:  21 May 2024 –  4 Jun 2024

**Comment by lixuna** [comment]
[How to Join the LFN as a Project](https://wiki.lfnetworking.org/display/LN/How+to+Join+the+LFN+as+a+Project)
Created by [Casey Cain](https://wiki.lfnetworking.org/display/~CaseyCain), last modified on [Mar 06, 2024](https://wiki.lfnetworking.org/pages/diffpagesbyversion.action?pageId=101352476&selectedPageVersions=5&selectedPageVersions=6)
If you're interested in having your project become a part of the Linux Foundation Networking (LFN), there's a well-defined process to follow. Below is a step-by-step guide to help you get started.

✅ Step 1: Familiarize Yourself with LFN Documentation
✅ Step 2: Evaluate Lifecycle States
✅ Step 3: Complete your Project Data Template
🚧 Step 4: Preliminary Outreach
- Contact TAC: Send an introductory email to the Technical Advisory Council (TAC) expressing your interest. 
[lfn-tac@lists.lfnetworking.org](mailto:lfn-tac@lists.lfnetworking.org)

Step 5: Review Period
- The Project Proposal and Project Data Template must be submitted to the TAC at least 2 weeks prior to the Review.
- During this time, the TAC will review your project, and you might be asked to provide additional information or clarify existing points.
- Engage in any required meetings with the Staff, TAC, or other committees for more in-depth evaluation.

Step 6: Formal Application
- Presentation: After the two week review period, present your Project Proposal to the LFN TAC.
- Wait for acknowledgment and review by LFN governance bodies, like the TAC or Governing Board.

Step 7: Final Approval and Onboarding
- Once approved, you'll be notified by LFN and guided through the onboarding process.
- Coordinate with your project LFN Staff on Onboarding your project to tooling and services
- Your project will be publicly announced in an LFN blog post, newsletter, or other suitable channels.

Step 8: Post-Induction
- You can now fully utilize LFN resources and contribute to the community.
- Begin tracking and improving your Community Badges criteria for future recognitions.
- Maintain active participation in Community Meetings and other LFN events.
- Track your projects activity with LFX Insights

By following these steps, you'll be well on your way to becoming an integral part of the LFN community. Good luck!
